import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#00382b",
        "secondary-fixed-dim": "#28dfb5",
        "surface-dim": "#131318",
        "tertiary-container": "#d57a20",
        "surface-tint": "#cabeff",
        "primary": "#cabeff",
        "surface-variant": "#35343a",
        "surface-container-high": "#2a292f",
        "on-primary-container": "#2b0088",
        "error": "#ffb4ab",
        "background": "#131318",
        "on-tertiary-fixed": "#2f1500",
        "primary-fixed": "#e6deff",
        "inverse-on-surface": "#303036",
        "surface-container-low": "#1b1b20",
        "surface-container-highest": "#35343a",
        "on-tertiary-container": "#432100",
        "on-surface": "#e4e1e9",
        "on-secondary-fixed": "#002118",
        "on-surface-variant": "#c9c4d8",
        "surface-bright": "#39383e",
        "on-primary": "#32009a",
        "tertiary-fixed": "#ffdcc3",
        "on-primary-fixed": "#1c0062",
        "tertiary": "#ffb77d",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e4e1e9",
        "primary-fixed-dim": "#cabeff",
        "inverse-primary": "#613de0",
        "surface-container": "#1f1f25",
        "secondary": "#41eec2",
        "on-tertiary": "#4d2600",
        "on-error": "#690005",
        "on-background": "#e4e1e9",
        "outline-variant": "#484555",
        "on-primary-fixed-variant": "#4918c8",
        "secondary-container": "#00d1a7",
        "error-container": "#93000a",
        "outline": "#938ea1",
        "on-tertiary-fixed-variant": "#6e3900",
        "on-secondary-fixed-variant": "#00513f",
        "tertiary-fixed-dim": "#ffb77d",
        "secondary-fixed": "#55fcd0",
        "primary-container": "#947dff",
        "surface": "#131318",
        "surface-container-lowest": "#0e0e13",
        "on-secondary-container": "#005441",
        "text-secondary": "#c9c4d8",
        "border": "#484555",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["JetBrains Mono", "monospace"],
        sans: ["Inter", "sans-serif"],
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-primary': 'linear-gradient(135deg, var(--accent-purple), #947dff)',
      },
      boxShadow: {
        'glow': '0 0 40px 6px rgba(124, 92, 252, 0.06)',
        'glow-hover': '0 0 60px 8px rgba(124, 92, 252, 0.1)',
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
