[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
arc_testnet = "https://rpc.arc.testnet.circle.com"

[etherscan]
arc_testnet = { key = "placeholder", url = "https://explorer.arc.testnet.circle.com/api" }